Logout
diversi-tech/kostiner-tenders-back pull request #21
Opened 2024-07-25 12:28 UTC by SaraHaouzi

2024-07-27 20:35 UTC, sariwaisbeker requested changes
השתדלתי לעשות רביו יסודי, על הלוגיקה האמיתית של הlogin פחות העזתי להעיר...

2024-07-27 20:35 UTC, sariwaisbeker commented on dal/auth_repo.py
> +        # print("list", list(self.user_collection.find({})))
אין user_collection כתכונה תשתמשי בcollection

2024-07-28 10:25 UTC, SaraHaouzi commented on .env
> +COLLECTIONS=["users","products","tenders","invoices","subscribers"]
אפשר למחוק אותו

2024-07-28 10:26 UTC, SaraHaouzi commented on app/app.py
> +CORS(app, supports_credentials=True, resources={r"/*": {"origins": "http://localhost:5174"}})
שינתי את זה למה למעודכן יותר מה שאת אמרת

2024-07-28 10:26 UTC, SaraHaouzi commented on app/app.py
> +api = Api()
אצלי יש רק שורה אחת וזה השורה מההערה למעלה

2024-07-28 10:27 UTC, SaraHaouzi commented on app/app.py
> +api.add_namespace(namespace_user, path='/users')
מחקתי את השורה האחרונה כנראה בטעות

2024-07-28 10:27 UTC, SaraHaouzi commented on controllers/login_controller.py
> +        }
פותר בעיות של CORS לפעמים

2024-07-28 10:27 UTC, SaraHaouzi commented on app/app.py
> +from controllers.subscription_registration_controller import nameSpace_subscription
מחקתי את זה

2024-07-28 10:28 UTC, SaraHaouzi commented on app/app.py
> +import middlewares
לא ככ הבנתי מה לשנות פה זה מיבא את הmiddlewares שלפני הכניסה לאתר

2024-07-28 10:28 UTC, SaraHaouzi commented on dal/auth_repo.py
> +        # print("list", list(self.user_collection.find({})))
שיניתי את זה

2024-07-28 10:32 UTC, sariwaisbeker commented on services/user_service.py
> +from functools import wraps
????

2024-07-28 10:34 UTC, sariwaisbeker commented on app/app.py
> +import middlewares
את מייבאת את הקבצים שרת צריכה אח"כ זה עצמו מייבא קובץ __init__ של הpackage לכאורה ייבוא מיותר

2024-07-28 10:35 UTC, SaraHaouzi commented on app/app.py
> +import middlewares
הבנתי מה את אומרת אני יסדר את זה עכשו

2024-07-28 10:35 UTC, sariwaisbeker commented on app/app.py
> +CORS(app, supports_credentials=True, resources={r"/*": {"origins": "http://localhost:5174"}})
אני רק הוספתי את מה שהיה נראה לי תבדקי שזה באמת ככה.
אין לי באמת מושג בזה.

2024-07-28 10:37 UTC, SaraHaouzi commented on app/app.py
> +import middlewares
סודר הענין

2024-07-28 10:38 UTC, sariwaisbeker commented on app/app.py
> +api = Api()
אני מתכוונת לזה:

> api = Api()

2024-07-28 10:40 UTC, SaraHaouzi commented on services/user_service.py
> +from functools import wraps
החזרתי אותם זה באמת היה בטעות
סורי גם על זה

2024-07-28 10:40 UTC, SaraHaouzi commented on dal/tender_repo.py
> -        return result_list
שוב שרי לא ככ הבנתי באיזה פונקציה להשים את זה

2024-07-28 10:41 UTC, SaraHaouzi commented on controllers/login_controller.py
> -        }
זה באמת פותר בעיות CORS

2024-07-28 10:55 UTC, sariwaisbeker commented on dal/tender_repo.py
> -        return result_list
זה פונקציה בפני עצמה
```python
    def get_by_category(self, category, search_date, start_date, end_date):
        print(f'tender_repo get_by_category category: {category}')
        query = {
            '$and': [
                {'category': category},
                {'published_date': {'$gte': start_date}},
                {'published_date': {'$lte': end_date}}
            ]
        }
        if search_date > start_date:
            query['$and'].append({'published_date': {'$lte': search_date}})
            print(query['$and'][3])
        list_category = (self.collection
                         .find(query)
                         .sort('published_date', -1)
                         .limit(100))
        result_list = list(list_category)
        return result_list

```
שימי לב שקוראים לזה מservices/tender_service.py

2024-07-28 11:01 UTC, SaraHaouzi commented on dal/tender_repo.py
> -        return result_list
סידרתי את זה 
לא היתה לי פונקציה כזאת בכלל העתקתי את כולה

2024-07-28 11:01 UTC, SaraHaouzi commented on controllers/user_controller.py
> -    @jwt_required()
כן כל פונקציה חייבת לקבל JWT

2024-07-28 11:18 UTC, sariwaisbeker commented
מצוין!!
תעשי merge

2024-07-28 11:20 UTC, merged